### ISSUE TITLE
How did it go with Next.JS?

### ISSUE THREAD

**Issue by andymantell** [ianhomer/try-next-gds#1]
Hi Ian,

I see you've been trying out my package with Next.JS... How did it go? Were there any issues you encountered? I have not yet tried this myself so I am quite interested to know what happened.

And for that matter, https://github.com/ianhomer/try-govuk-react-jsx as well - was everything ok?

Thanks very much,

Andy

**Comment by ianhomer** [comment]
Hi Andy,

Yes - really like what you've put together with the govuk react jsx package. So far no glitches, all smooth going. Looking forward to using it more, hopefully we can help contribute :)

Thanks,

Ian

**Comment by andymantell** [comment]
Hi Ian,

That's great to hear, glad it's working for you. Any problems let me know and by all means contribute if you wish to, I am open to that.

Heads up that the 3.9.x+ release is taking me a little longer than usual as it has caused all sorts of issues with the test suite, but hopefully it won't be too much longer.

Cheers,

Andy

**Comment by ianhomer** [comment]
Thanks, appreciated. Team will be using extensively in the coming weeks, currently experimenting with extensions + webpack optimisation. We'll share feedback with you & keen to collaborate.
